import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav style={{ padding: 16, margin: 8 }}>
          <Link href="/" style={{ padding: 8 }}>
            Home
          </Link>
          <Link href="/about" style={{ padding: 8 }}>
            About
          </Link>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
